## cacheMatrix.R
## Functions below allow for the caching of the inverse
## of a matrix, saving computational time of having to 
## repeatedly calculate the inverse if required.

## makeCacheMatrix:
## creates a matrix object that can be cached

makeCacheMatrix <- function(x = matrix()) {
  Inv <- NULL
  set <- function(y) {
    x <<- y
    Inv <<- NULL
  }
  get <- function() x
  setInv <- function(inverse) Inv <<- inverse
  getInv <- function() Inv
  list(set = set,
       get = get,
       setInv = setInv,
       getInv = getInv)
}


## cacheSolve:
## Solves the inverse of the object generated by 
## makeCacheMatrix (through the use of the 'solve' function).
## However, the function first checks of the inverse is not 
## already available in the cache - in which case it simply
## retrieves it, instead of recalculating.

cacheSolve <- function(x, ...) {
  Inv <- x$getInv()
  if(!is.null(Inv)) {
    message("getting cached data")
    return(Inv)
  }
  data <- x$get()
  Inv <- solve(data, ...)
  x$setInv(Inv)
  Inv
}

## Testing functionality: simple check to see
## if the inverse is calculated; and once
## calculated, retrieved from cache.

x <- rnorm(16)
m1 <- matrix(x, nrow = 4, ncol = 4)
d <- makeCacheMatrix(m1)
cacheSolve(d)
### repeat to check if cached matrix is used 2nd time
cacheSolve(d)